### ISSUE TITLE
[BUG] tektited panics in standalone embedded mode when using kafkactl v3.5.1 

### ISSUE THREAD

**Issue by devguyio** [spirit-labs/tektite#73]
## Current Behavior

When running tektited in standalone mode with
```shell
tektited --config cfg/standalone.conf
```

and kafkactl v3.5.1 for any operation like

```shell
kafkactl get brokers
```

tektited panics with

```shell
> tektited --config cfg/standalone.conf
2024-05-30 11:52:46.687012	INFO	tektite server 0 started
Panic occurred in tektite unsupported metadata api version 9
goroutine 2049 [running]:
runtime/debug.Stack()
	/home/abd4lla/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.linux-amd64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/home/abd4lla/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.linux-amd64/src/runtime/debug/stack.go:16 +0x13
github.com/spirit-labs/tektite/common.PanicHandler()
	/home/abd4lla/GolandProjects/github.com/spirit-labs/tektite/common/panic_handler.go:18 +0x5f
panic({0x17077a0?, 0xc0019a1e30?})
	/home/abd4lla/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.linux-amd64/src/runtime/panic.go:770 +0x132
github.com/spirit-labs/tektite/kafkaserver.(*connection).handleMetadata(0x0?, 0x0?, {0xc0006f601f?, 0xc00063c188?, 0xff?}, 0x197e701?)
	/home/abd4lla/GolandProjects/github.com/spirit-labs/tektite/kafkaserver/api_handler.go:416 +0x914
github.com/spirit-labs/tektite/kafkaserver.(*connection).handleApi(0xc001aa3380, 0xc000977dd0, 0x3, 0x9, {0xc0006f601f, 0x5, 0x1fe1}, 0x9, 0xc0004ab9c8)
	/home/abd4lla/GolandProjects/github.com/spirit-labs/tektite/kafkaserver/api_handler.go:64 +0x21a
github.com/spirit-labs/tektite/kafkaserver.(*connection).handleMessage(0xc001aa3380, {0xc0006f6004, 0x20, 0x1ffc})
	/home/abd4lla/GolandProjects/github.com/spirit-labs/tektite/kafkaserver/server.go:262 +0x2a7
github.com/spirit-labs/tektite/kafkaserver.(*connection).readMessage(0xc001aa3380)
	/home/abd4lla/GolandProjects/github.com/spirit-labs/tektite/kafkaserver/server.go:214 +0x22b
github.com/spirit-labs/tektite/kafkaserver.(*connection).readLoop(0xc001aa3380)
	/home/abd4lla/GolandProjects/github.com/spirit-labs/tektite/kafkaserver/server.go:176 +0x6a
github.com/spirit-labs/tektite/common.Go.func1()
	/home/abd4lla/GolandProjects/github.com/spirit-labs/tektite/common/spawn.go:38 +0x93
created by github.com/spirit-labs/tektite/common.Go in goroutine 172
	/home/abd4lla/GolandProjects/github.com/spirit-labs/tektite/common/spawn.go:31 +0x138
```

## Expected Behavior

When getting an unsupported version a proper response with the `UNSUPPORTED_VERSION` [1] should be returned. 

[1] https://kafka.apache.org/protocol.html#protocol_error_codes

## Steps to Reproduce

1. Run tektited with `tektited --config cfg/standalone.conf`
2. Run kafkactl with `BROKERS="localhost:8880" kafkactl get brokers`

**Comment by devguyio** [comment]
@purplefox I took a deeper look and came across this check. Is there a reason behind supporting only version 3? That's a very old version given that now Kafka Metadata is at [version 12](https://kafka.apache.org/protocol.html#The_Messages_Metadata) 

https://github.com/spirit-labs/tektite/blob/d22b0bb9d4d679a8a01f91802b033cd3f7b13888/kafkaserver/api_handler.go#L415-L417

**Comment by purplefox** [comment]
That's interesting, I wonder if kafkactl is abusing the KafkaAPI?

We only support metadata api version 3, and we advertise that in the ApiVersions request:

https://github.com/spirit-labs/tektite/blob/main/kafkaserver/api_handler.go#L861

The tool should be first calling ApiVersions to see what versions of the Api are supported and only sending requests to other api endpoints within those version ranges. As we report 3, it should never send a request with version 9.

I suspect they only tested it against modern Kafka which sends back 9 is supported ?

In any case we shouldn't panic, we should send back an error. So we should fix that.
